[email_accounts]
"info.solvitrontech@gmail.com" = "jvpp icnc kbdc vmtp"
"mdarif92@gmail.com" = "your_app_password2"
"yourgmail3@gmail.com" = "your_app_password3"
"yourgmail4@gmail.com" = "your_app_password4"
"yourgmail5@gmail.com" = "your_app_password5"