[email_accounts]
"commercialcleaningbest@gmail.com" = "uftl wdaz frbb cgda"
"commercialcleaningm@gmail.com" = "pzbp przh rmul sspz"
"melbournecommercialcleaning2@gmail.com" = "wusv clda ogbr knun"
"ccleaning82@gmail.com" = "rbte bvww wvde ywij"
"yourgmail5@gmail.com" = "your_app_password5"
